"""fix iqos model. update fild sale_price

Revision ID: 5298e9d4d330
Revises: 
Create Date: 2025-10-28 18:31:31.699458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5298e9d4d330'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Devices_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Iqos_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Terea_category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('description', mysql.LONGTEXT(), nullable=False),
    sa.Column('image', mysql.LONGTEXT(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('nalichie', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('new', mysql.TINYINT(), nullable=False),
    sa.Column('hit', mysql.TINYINT(), nullable=True),
    sa.Column('color', mysql.ENUM('Красный', 'Черный', 'Бежевый', 'Синий', 'Оранжевый', 'Зеленый', 'Фиолетовый', 'Желтый', 'Серый'), nullable=False),
    sa.Column('ref', sa.VARCHAR(length=256), nullable=False),
    sa.Column('type', sa.VARCHAR(length=256), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['Devices_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Iqos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('model', mysql.TEXT(), nullable=True),
    sa.Column('description', mysql.LONGTEXT(), nullable=False),
    sa.Column('image', mysql.LONGTEXT(), nullable=False),
    sa.Column('price', sa.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('color', mysql.ENUM('Красный', 'Черный', 'Бежевый', 'Синий', 'Оранжевый', 'Зеленый', 'Фиолетовый', 'Желтый', 'Серый'), nullable=False),
    sa.Column('new', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('hit', mysql.TINYINT(), nullable=True),
    sa.Column('exclusive', mysql.TINYINT(), nullable=True),
    sa.Column('nalichie', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('ref', sa.VARCHAR(length=256), nullable=False),
    sa.Column('type', sa.VARCHAR(length=256), nullable=False),
    sa.Column('sale_price', sa.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('id_category', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_category'], ['Iqos_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Terea',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('description', mysql.LONGTEXT(), nullable=False),
    sa.Column('image', mysql.LONGTEXT(), nullable=False),
    sa.Column('imagePack', sa.VARCHAR(length=256), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=0), nullable=False),
    sa.Column('pricePack', sa.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('has_capsule', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('flavor', mysql.SET('Табачный вкус', 'Фруктовый вкус', 'Ментол', 'Экзотические'), nullable=False),
    sa.Column('country', mysql.TEXT(), nullable=False),
    sa.Column('brend', sa.VARCHAR(length=256), nullable=False),
    sa.Column('strength', mysql.ENUM('Легкие', 'Средние', 'Крепкие'), nullable=False),
    sa.Column('nalichie', mysql.TINYINT(display_width=1), nullable=False),
    sa.Column('new', mysql.TINYINT(), nullable=False),
    sa.Column('hit', mysql.TINYINT(), nullable=True),
    sa.Column('ref', sa.VARCHAR(length=256), nullable=False),
    sa.Column('type', sa.VARCHAR(length=256), nullable=False),
    sa.Column('terea_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['terea_id'], ['Terea_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Terea')
    op.drop_table('Iqos')
    op.drop_table('Devices')
    op.drop_table('Terea_category')
    op.drop_table('Iqos_category')
    op.drop_table('Devices_category')
    # ### end Alembic commands ###
