"""fix admin user

Revision ID: 6e43d39dd3cf
Revises: bf4440b8f9ea
Create Date: 2025-10-31 14:06:12.710460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6e43d39dd3cf'
down_revision: Union[str, Sequence[str], None] = 'bf4440b8f9ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.drop_index(op.f('email'), table_name='admin_users')
    op.drop_column('admin_users', 'full_name')
    op.drop_column('admin_users', 'email')
    
    # 保留外键约束的修改
    op.drop_constraint(op.f('ordered_products_ibfk_1'), 'ordered_products', type_='foreignkey')
    op.create_foreign_key(None, 'ordered_products', 'Orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ordered_products', type_='foreignkey')
    op.create_foreign_key(op.f('ordered_products_ibfk_1'), 'ordered_products', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column('admin_users', sa.Column('email', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('admin_users', sa.Column('full_name', mysql.VARCHAR(length=255), nullable=True))
    op.create_index(op.f('email'), 'admin_users', ['email'], unique=True)
